name: lab4-workflow
on:
  # workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    branches:
    - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: npm ci
    - name: lint code
      run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: npm ci
    - name: test code
      id: code-test
      continue-on-error: true
      run: npm run test
    - name: publish test report
      if: steps.code-test.outcome == 'failure'
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: test.json
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: npm ci
    - name: build code
      run: npm run build
    - name: upload build
      uses: actions/upload-artifact@v3
      with:
        name: dist-files
        path: dist


  in-between-job:
    needs: [build]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      artifact-name: dist-files


  deploy:
    runs-on: ubuntu-latest
    needs: [in-between-job]
    steps:
    - name: get dist-files
      uses: actions/download-artifact@v3
      with:
        name: dist-files
    - name: list files
      run: ls -ahl
    - name: deploy app
      run: echo "deploying ..."
