name: workflow
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    branches:
    - master
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        node_version: ["12", "14", "16"]
    runs-on: ${{matrix.os}}
    steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '${{matrix.node_version}}'
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-deps
      uses: actions/cache@v4
      with:
        key: dependencies-${{hashFiles('**/package-lock.json')}}
        path: node_modules
    - name: install dependencies
      if: steps.cache-deps.cache-hit != 'true'
      run: npm ci
    - name: build app
      run: npm run build
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist

