name: reusable-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "this is the artifact produced by the build step of the caller workflow"
        required: true
        type: string
jobs:
  in-between:
    runs-on: ubuntu-latest
    steps:
    - name: get artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.artifact-name}}
    - name: list content
      run: ls -alh
      

