name: reusable-workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "this is the artifact produced by the build step of the caller workflow"
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true
    outputs:
      food: 
        value: ${{jobs.in-between.outputs.food-job}}
jobs:
  in-between:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{secrets.username}}
          MONGO_INITDB_ROOT_PASSWORD: ${{secrets.password}}
    outputs:
      food-job: ${{steps.output-generator.outputs.food-step}}
    steps:
    - name: get artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{inputs.artifact-name}}
    - name: list content
      run: ls -alh
    - name: generate output
      id: output-generator
      run: echo "food-step=PIZZA" > $GITHUB_OUTPUT
      

