name: second-workflow
on: [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: npm ci
    - name: lint code
      run: npm run lint
  build:
    needs: [lint]
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-22.04, windows-latest]
        node-version: [20, 12]
        include:
        - runner: ubuntu-22.04
          node-version: 16
        exclude:
        - runner: ubuntu-latest
          node-version: 20
        - runner: windows-latest
          node-version: 18
    runs-on: ${{matrix.runner}}
    continue-on-error: true
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node-version}} 
    - name: cache dependencies
      id: cache-dep
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: npm ci
    - name: build app
      run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: deploy app
      run: echo "deploying ..."